# Generated by Django 5.0.2 on 2025-04-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('book_genre', models.CharField(choices=[('F', 'Fiction'), ('N', 'Non Fiction'), ('D', 'Drama'), ('T', 'Thriller'), ('C', 'Comedy'), ('R', 'Romance')], max_length=20)),
            ],
            options={
                'ordering': ['book_genre'],
            },
        ),
    ]
