# Generated by Django 5.0.2 on 2025-04-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_grade', models.CharField(choices=[(1, 'Grade I'), (2, 'Grade II'), (3, 'Grade III'), (4, 'Grade IV'), (5, 'Grade V')], max_length=10)),
                ('student_section', models.CharField(max_length=1)),
                ('teacher_name', models.CharField(max_length=20)),
                ('total_marks', models.IntegerField(max_length=2)),
                ('admission_date', models.DateField()),
                ('student_disablity', models.TextField()),
            ],
        ),
    ]
