# Generated by Django 5.0.2 on 2025-04-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom_app',
            name='total_marks',
            field=models.IntegerField(),
        ),
    ]
