# Generated by Django 5.0.2 on 2025-04-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom_app', '0002_alter_classroom_app_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom_app',
            name='student_grade',
            field=models.IntegerField(choices=[(1, 'Grade I'), (2, 'Grade II'), (3, 'Grade III'), (4, 'Grade IV'), (5, 'Grade V')], max_length=10),
        ),
    ]
