# Generated by Django 5.0.2 on 2025-04-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom_app', '0003_alter_classroom_app_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom_app',
            name='student_grade',
            field=models.CharField(choices=[('A', 'Grade I'), ('B', 'Grade II'), ('C', 'Grade III'), ('D', 'Grade IV'), ('E', 'Grade V')], max_length=10),
        ),
    ]
