# Generated by Django 5.0.2 on 2025-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prisoner_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('block_number', models.CharField(choices=[('A', 'Block A'), ('B', 'Block B'), ('C', 'Block C'), ('D', 'Block D')], max_length=1)),
                ('cell_number', models.IntegerField()),
                ('admission_date', models.DateField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('crime', models.TextField()),
            ],
        ),
    ]
