# Generated by Django 5.0.2 on 2025-04-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prison_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prisoner',
            options={'ordering': ['block_number', 'cell_number']},
        ),
    ]
